name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: init_submodules
      run: git submodule update --init --recursive
    - name: build
      run: make
    - name: run
      run: make run
